language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=YES STRUS_WITH_WEBSERVICE=NO
# Sat Jan 12: strusPattern is currently disabled for clang C++ with PHP/LUA, because we reach the maximum job length. It is tested with strusBindings
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=YES STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=YES STRUS_WITH_WEBSERVICE=NO
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES STRUS_WITH_VECTOR=YES STRUS_WITH_PATTERN=YES STRUS_WITH_WEBSERVICE=NO
# WebService
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=YES
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=YES

sudo: required
branches:
  only:
    - master
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- dist/travis/script.sh
